# Generated by Django 6.0.2 on 2026-02-24 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('freelancer', 'Freelancer'), ('recruiter', 'Recruiter')], max_length=20)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('skills', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('job_description', models.TextField(blank=True)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
